<h3>Správce textů</h3>
<style>
	.pathtext:hover{
		cursor:pointer;
	}
</style>
<?
if(isset($_POST["textyarea"])) {
	$i = 0;
	while($i != sizeof($_POST["textyarea"])) {
		$stmt = $mysql->prepare("UPDATE ck_recenze_texty SET content=? WHERE pathinfo=?");
		$stmt->bind_param("ss", $_POST["textyarea"][$i], $_POST["cesty"][$i]);
		$stmt->execute();
		$stmt->close();
		++$i;
	} ?>
	<div class="alert alert-success" role="alert"><span class="alert-heading">Změny uloženy a zapsány do DB</span></div>
<? }

$stmt = $mysql->prepare("SELECT pathinfo,content FROM ck_recenze_texty");
$stmt->execute();
$stmt->store_result();
$stmt->bind_result($path,$txt);

?>
<form method="post" action="#">
	<? $i = 0; while($stmt->fetch()) { ?>

		<span class="d-block pathtext" onclick="showArea(<?=$i?>);"><?=$path?></span>
		<textarea name="textyarea[]" class="xarea" style="width:100%;height:500px<?=($i > 1 ? ";display:none" : "")?>;"><?=$txt?></textarea>
		<input type="hidden" name="cesty[]" value="<?=$path?>">
		<br />
	<? ++$i;
	}
	$stmt->close();
	?>
	<button class='btn btn-primary'>Uložit</button>
</form>
<script>
	function showArea(which) {

		let len = document.getElementsByClassName("xarea").length;
		let ar = document.getElementsByClassName("xarea")[which];
		let path = document.getElementsByClassName("pathtext")[which];

		for(let i = 0; i < len; i++) {
			document.getElementsByClassName("xarea")[i].style.maxHeight = "0";
			document.getElementsByClassName("xarea")[i].style.height = "initial";
			document.getElementsByClassName("xarea")[i].style.display = "none";
			document.getElementsByClassName("pathtext")[i].style.marginTop = "initial";
			document.getElementsByClassName("pathtext")[i].style.fontWeight = "initial";
		}

		ar.style.height = "500px";
		ar.style.maxHeight = "initial";
		ar.style.display = "block";

		path.style.marginTop = "30px";
		path.style.fontWeight = "bold";

		console.log(ar);
	}

	window.addEventListener("DOMContentLoaded", showArea(0));
</script>