<h1>Vítejte na Recenze Cestovek</h1>
<br />
Cestovní kanceláře nabízejí různé úrovně služeb a každý klient má různé zkušenosti.
<br /><br />
Lidé se při výběru dovolené pořádané cestovní kanceláří dělí na dvě skupiny. Jedna jezdí jen s tou „svou“ cestovkou. Zde může nastat problém, že kancelář nepořádá zájezdy do destinace kam máte v plánu se podívat. Výhodou je, že pokud s cestovkou létáte opravdu často, můžete dostávat slevy. Druhá skupina turistů si nejprve vybere destinaci, hotel a pak teprve zjišťuje, se kterou cestovkou se tam létá. Ti většinou letí každý rok s někým jiným.    
<br /><br />
Přejeme Vám šťastnou ruku při volbě jedné z cestovek pro Vaši dovolenou a bez ohledu na to, ke které skupině patříte, nezapomeňte se po návratu podělit o své zkušenosti, ať už jsou dobré nebo špatné. Na stránkách naleznete seznam a recenze všech větších cestovek, které v ČR prodávají zájezdy. Ke každé můžete napsat vlastní recenze a to jak pozitivní tak i negativní.
<br /><br /><br />

<a href="<?=$config["baseUrl"]?>/recenze">Přejít na seznam a recenze cestovek</a>