<h1>Doporučení při výběru silného hesla:</h1>
<br />
<ul>
	<li>Používejte znaky, písmena a čísla</li>
	<li>Střídejte velké písmena s malými</li>
	<li>Vaše heslo by se nemělo shodovat s uživatelským jménem</li>
	<li>Nepoužívejte krátké hesla, doporučuje se minimálně 12 znaků</li>
	<li>Heslo by nemělo obsahovat běžné slova, jména ani datumy</li>
	<li>Nepoužívejte stejné heslo na více webech</li>
</ul>